# Generated by Django 4.0.5 on 2022-06-13 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comment', '0002_alter_books_author'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userscomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
